### ISSUE TITLE
Find a name for the team

### ISSUE THREAD

**Issue by mariamar95** [mariamar95/jan-hackathon#2]

**Comment by phloreenm** [comment]
I've initially named the group as “Cloud Surfers” as referring to surfers on Clouds as an infrastructure, as the servers which run there, the SW and so on. Surfing on these clouds...

**Comment by abz2489** [comment]
Savvy Savers or Savvy Saving

**Comment by abz2489** [comment]
My above suggestions were meant for the project name. I've posted them there instead.

**Comment by hhw1101** [comment]
I actually like the names you had for the project names as the team name instead. 
I quite liike Savvy Savers as a team name.
