### ISSUE TITLE
Create a custom 404.html page

### ISSUE THREAD

**Issue by CallumDennisIE** [mariamar95/jan-hackathon#36]

**Comment by CallumDennisIE** [comment]
GitHub pages will use a default 404 page if an HTML 404 Response is given. This page can be customised by adding a 404.html to the project, GitHub pages will show that instead:

https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site

**Comment by phloreenm** [comment]
@MHickey2 Could you edit my Pull Request to your like?
