### ISSUE TITLE
Brainstorm Ideas

### ISSUE THREAD

**Issue by mariamar95** [mariamar95/jan-hackathon#4]

**Comment by CallumDennisIE** [comment]
A finance calculator that displays a breakdown of annual spending based on the [5 Bucket Money Management Theory](https://medium.datadriveninvestor.com/how-to-manage-money-5b490e9d3d63).

- Users can enter their spending in relation to the different buckets. 
- Use [Chart.js](https://www.chartjs.org/) to display a title for each Bucket.
- Use [CSS Materialize](https://materializecss.com/) as the CSS Framework
- Users can compare their spending breakdown vs. recommended allocations.
- Possibly allow users to convert their saving currency to others using currency converter API (i.e. [fixer.io](https://fixer.io/))
- Possibly allow users to save the chart as HTML. (i.e. [html-to-pdf-js](https://www.npmjs.com/package/html-to-pdf-js))
