### ISSUE TITLE
Get bucket name from calculate.html form in JS

### ISSUE THREAD

**Issue by CallumDennisIE** [mariamar95/jan-hackathon#70]

**Comment by CallumDennisIE** [comment]
- script.js and calculate.html will have to be updated.
- Need to change value from 1-6, to the actual bucket name.
- Then get the value and add it to the get_user_input function
- The update the create table function to display the bucket name

**Comment by CallumDennisIE** [comment]
This currently is partially implemented.
The bucket names will be retrieved, however bucket names on newly added rows with the '+' button, show as 'unassigned'

**Comment by phloreenm** [comment]
So it needs a refresh, like the Materialize lib is doing, right?
