### ISSUE TITLE
Fix chrome violation

### ISSUE THREAD

**Issue by CallumDennisIE** [mariamar95/jan-hackathon#88]

**Comment by CallumDennisIE** [comment]
[Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

**Comment by phloreenm** [comment]
Violations are just Warnings, not errors, so we shouldn't worry too much about that. What do you say?
