### ISSUE TITLE
Create Wireframes-Mockups

### ISSUE THREAD

**Issue by mariamar95** [mariamar95/jan-hackathon#9]

**Comment by CallumDennisIE** [comment]
Initial Mockup using Chart.js to display charts:

- [Live Site](https://callumdennisie.github.io/test-chartjs/)
- [Repo](https://github.com/CallumDennisIE/test-chartjs)

**Comment by mariamar95** [comment]
That's great work done in no time! Can't wait to discuss it with the team tomorrow

**Comment by CallumDennisIE** [comment]
**Wireframes:**
- Wireframe for the intro page
- Wireframe for form input page with charts

Include Fonts and colour pallete

**Comment by mariamar95** [comment]
Dayana has shared the mockus with us on our slack channel. I am closing this issue for her
